name: numba
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - watermark
  - numba 
  - dask 
  - matplotlib
  - cupy
  - scipy 
  - numpy
  - cudatoolkit==9.2
  - rise
  - numpy
  - snakeviz
  - line_profiler
  - cython
  - jupyter_contrib_nbextensions
